### ISSUE TITLE
What about a special event "mouseapproach"

### ISSUE THREAD

**Issue by LeMisterV** [srobbin/jquery-approach#3]
Hi,

Do you know about jQuery "special events" ?
Your idea of a mouse approach plugin is very good. Why not making an event of it ?

Here is an article describing how to define special events. I'm sure you could use it for your mouse approach idea.
http://brandonaaron.net/blog/2009/03/26/special-events

It would be great to be able to do something like :
$('mySelector').bind('mouseapproach', function() {alert('Don't go there !!');});

Regards,

Nico

**Comment by srobbin** [comment]
This is a good idea. I had considered using something along those lines, but I couldn't find a natural way to set the approach boundary. i.e. Only activate the approach animation within 300px of the object. So, I chose to treat it as a regular plugin.

Thanks for the feedback.

-Scott

**Comment by LeMisterV** [comment]
Hi,

I just created a new jquery plugin that implements two special events : "mouseapproach" and "mouseretreat".

As your plugin does more than just reporting that mouse approaches of retreats, I didn't create a fork, but a new repository. But your script could probably benefit from mine.

the gitHub repository for my plugin :
http://github.com/LeMisterV/jquery-distanceListener

There's no comments or doc for my script, I had no time for this. But I'll try to write some soon. But I created a demo file, so you can see a use example.

Regards,

Nico
